---
title: "Sumo Match Sheet"
author: "Ryan McCorvie"
format: 
  html:
    page-layout: full
editor: visual
---

```{r}
#| echo: false
#| output: false

library(tidyverse)
library(plotly)
library(gt)
library(DT)
source( "sumo_api.R" )
source( "elo_functions.R")

basho_id = current_basho()
matches_cache <- readRDS( "matches_cache.Rdata")
elo_history   <- readRDS( "elo_history.Rdata")
sumo_name_t   <- readRDS( "sumo_name_t.Rdata")
#all_rikishi() |> select( rikishiId = id, shikona = shikonaEn )


```

## Elo Trends for `r basho_description(basho_id)`

```{r}
#| echo: false

day <- 7

banzuke_rank <- basho_sumo_rank( basho_id ) |>
  filter( rank_name != "Jonokuchi", rank_name != "Jonidan", rank_name != "Sandanme", rank_name != "Makushita", rank_name != "Juryo" )


banzuke_elo <- banzuke_rank |> left_join( elo_as_of( basho_id, 1 ), by="rikishiId" ) |>
  mutate( elo = coalesce( elo, 1500), ordinal_rank = 1:n())  |>
  rename( pre_tournament_elo = elo ) |>
  left_join( elo_as_of( basho_id, day ), by="rikishiId" ) |>
  left_join( sumo_name_t, by="rikishiId" )


pp<- ggplot( banzuke_elo, aes( ordinal_rank, elo, color=rank_name, text=shikona)) +
  geom_segment( aes( x=ordinal_rank, y=pre_tournament_elo, xend=ordinal_rank, yend = elo), arrow=arrow(length=unit(0.15, "inches"))) +
  geom_point(size=1.5) +
  scale_color_brewer( palette ="Set2") +
  labs( title = paste0("Elo Movement" ))

ggplotly(pp, tooltip = "text")

```




## Match Analysis for `r basho_description(basho_id)`

### Day 7

```{r}
#| echo: false

match_sheet <- get_match_sheet( basho_id,  7 )

match_sheet <- match_sheet |> 
  mutate( 
    record_east = paste0( wins_east, "-", losses_east),
    record_west = paste0( wins_west, "-", losses_west),
    `Elo Gap`    = paste( round(elo_mismatch), ifelse( elo_east<=elo_west, "←","→"))
  ) 

prediction_sheet <- match_sheet |> 
  select( `Match` = matchNo, East = eastShikona, `Record E` = record_east, `Elo E` = elo_east, `Win Prob E`=pwin_east, `Odds E`=odds_east, `Surprisal E` = surprisal_east, `Elo Gap`, `Suprisal W` = surprisal_west,  `Odds W` = odds_west, `Win Prob W` = pwin_west, `Elo W` = elo_west,`Record W` = record_east,  West = westShikona )


gt( prediction_sheet) |>
  tab_options(table.width = pct(90)) |> 
  tab_options(table.font.size = "14px") |> 
  fmt_number(
    columns = c(`Elo E`, `Elo W`, `Elo Gap` ),
    use_seps = F,
    decimals = 0  # sets the number of decimal places
  ) |> 
  fmt_number(
    columns =  c( `Win Prob E`, `Odds E`, `Surprisal E`, `Win Prob W`, `Odds W`, `Suprisal W`),
    decimals = 2
  ) |> 
  cols_align(
    align = "right",
    columns = `Elo Gap`   # replace with your column
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(
      columns = c( `Surprisal E`, `Elo Gap` )
    )
  )

```

### Day 6

```{r}
#| echo: false

match_sheet <- get_match_sheet( basho_id,  6 )

match_sheet <- match_sheet |> 
  mutate( 
    record_east = paste0( wins_east, "-", losses_east),
    record_west = paste0( wins_west, "-", losses_west),
    `Win` = ifelse( eastShikona == winnerEn, "←","→"),
    `Elo Gap`    = paste( round(elo_mismatch), ifelse( elo_east<=elo_west, "←","→"))
  ) 

post_sheet <- match_sheet |> 
select( `Match` = matchNo, East = eastShikona, `Record E` = record_east, `Elo E` = elo_east, `Win Prob E` = pwin_east, Win,  West = westShikona, `Record W` = record_west,  `Elo W` = elo_west, `Win Prob W` = pwin_west, Surprisal = surprisal)


gt( post_sheet) |>
  tab_options(table.width = pct(90)) |> 
  tab_options(table.font.size = "14px") |> 
  fmt_number(
    columns = c( `Elo W`, `Elo E` ),
    use_seps = F,
    decimals = 0  # sets the number of decimal places
  ) |> 
  fmt_number(
    columns =  c( Surprisal, `Win Prob E`, `Win Prob W`),
    decimals = 2
  ) |> 
  cols_align(
    align = "center",
    columns = `Win`   # replace with your column
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(
      columns = c( `Win Prob E`, `Win`, `Win Prob W` )
    )
  )

```


### Day 5

```{r}
#| echo: false

match_sheet <- get_match_sheet( basho_id,  5 )

match_sheet <- match_sheet |> 
  mutate( 
    record_east = paste0( wins_east, "-", losses_east),
    record_west = paste0( wins_west, "-", losses_west),
    `Win` = ifelse( eastShikona == winnerEn, "←","→"),
    `Elo Gap`    = paste( round(elo_mismatch), ifelse( elo_east<=elo_west, "←","→"))
  ) 

post_sheet <- match_sheet |> 
select( `Match` = matchNo, East = eastShikona, `Record E` = record_east, `Elo E` = elo_east, `Win Prob E` = pwin_east, Win,  West = westShikona, `Record W` = record_west,  `Elo W` = elo_west, `Win Prob W` = pwin_west, Surprisal = surprisal)


gt( post_sheet) |>
  tab_options(table.width = pct(90)) |> 
  tab_options(table.font.size = "14px") |> 
  fmt_number(
    columns = c( `Elo W`, `Elo E` ),
    use_seps = F,
    decimals = 0  # sets the number of decimal places
  ) |> 
  fmt_number(
    columns =  c( Surprisal, `Win Prob E`, `Win Prob W`),
    decimals = 2
  ) |> 
  cols_align(
    align = "center",
    columns = `Win`   # replace with your column
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(
      columns = c( `Win Prob E`, `Win`, `Win Prob W` )
    )
  )

```


### Day 4

```{r}
#| echo: false

match_sheet <- get_match_sheet( basho_id,  4 )

match_sheet <- match_sheet |> 
  mutate( 
    record_east = paste0( wins_east, "-", losses_east),
    record_west = paste0( wins_west, "-", losses_west),
    `Win` = ifelse( eastShikona == winnerEn, "←","→"),
    `Elo Gap`    = paste( round(elo_mismatch), ifelse( elo_east<=elo_west, "←","→"))
  ) 

post_sheet <- match_sheet |> 
select( `Match` = matchNo, East = eastShikona, `Record E` = record_east, `Elo E` = elo_east, `Win Prob E` = pwin_east, Win,  West = westShikona, `Record W` = record_west,  `Elo W` = elo_west, `Win Prob W` = pwin_west, Surprisal = surprisal)


gt( post_sheet) |>
  tab_options(table.width = pct(90)) |> 
  tab_options(table.font.size = "14px") |> 
  fmt_number(
    columns = c( `Elo W`, `Elo E` ),
    use_seps = F,
    decimals = 0  # sets the number of decimal places
  ) |> 
  fmt_number(
    columns =  c( Surprisal, `Win Prob E`, `Win Prob W`),
    decimals = 2
  ) |> 
  cols_align(
    align = "center",
    columns = `Win`   # replace with your column
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(
      columns = c( `Win Prob E`, `Win`, `Win Prob W` )
    )
  )

```


### Day 3

```{r}
#| echo: false

match_sheet <- get_match_sheet( basho_id,  3 )

match_sheet <- match_sheet |> 
  mutate( 
    record_east = paste0( wins_east, "-", losses_east),
    record_west = paste0( wins_west, "-", losses_west),
    `Win` = ifelse( eastShikona == winnerEn, "←","→"),
    `Elo Gap`    = paste( round(elo_mismatch), ifelse( elo_east<=elo_west, "←","→"))
  ) 

post_sheet <- match_sheet |> 
select( `Match` = matchNo, East = eastShikona, `Record E` = record_east, `Elo E` = elo_east, `Win Prob E` = pwin_east, Win,  West = westShikona, `Record W` = record_west,  `Elo W` = elo_west, `Win Prob W` = pwin_west, Surprisal = surprisal)


gt( post_sheet) |>
  tab_options(table.width = pct(90)) |> 
  tab_options(table.font.size = "14px") |> 
  fmt_number(
    columns = c( `Elo W`, `Elo E` ),
    use_seps = F,
    decimals = 0  # sets the number of decimal places
  ) |> 
  fmt_number(
    columns =  c( Surprisal, `Win Prob E`, `Win Prob W`),
    decimals = 2
  ) |> 
  cols_align(
    align = "center",
    columns = `Win`   # replace with your column
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(
      columns = c( `Win Prob E`, `Win`, `Win Prob W` )
    )
  )

```


### Day 2

```{r}
#| echo: false

match_sheet <- get_match_sheet( basho_id,  2 )

match_sheet <- match_sheet |> 
  mutate( 
    record_east = paste0( wins_east, "-", losses_east),
    record_west = paste0( wins_west, "-", losses_west),
    `Win` = ifelse( eastShikona == winnerEn, "←","→"),
    `Elo Gap`    = paste( round(elo_mismatch), ifelse( elo_east<=elo_west, "←","→"))
  ) 

post_sheet <- match_sheet |> 
select( `Match` = matchNo, East = eastShikona, `Record E` = record_east, `Elo E` = elo_east, `Win Prob E` = pwin_east, Win,  West = westShikona, `Record W` = record_west,  `Elo W` = elo_west, `Win Prob W` = pwin_west, Surprisal = surprisal)


gt( post_sheet) |>
  tab_options(table.width = pct(90)) |> 
  tab_options(table.font.size = "14px") |> 
  fmt_number(
    columns = c( `Elo W`, `Elo E` ),
    use_seps = F,
    decimals = 0  # sets the number of decimal places
  ) |> 
  fmt_number(
    columns =  c( Surprisal, `Win Prob E`, `Win Prob W`),
    decimals = 2
  ) |> 
  cols_align(
    align = "center",
    columns = `Win`   # replace with your column
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(
      columns = c( `Win Prob E`, `Win`, `Win Prob W` )
    )
  )

```


### Day 1

```{r}
#| echo: false

match_sheet <- get_match_sheet( basho_id,  1 )

match_sheet <- match_sheet |> 
  mutate( 
    record_east = paste0( wins_east, "-", losses_east),
    record_west = paste0( wins_west, "-", losses_west),
    `Win` = ifelse( eastShikona == winnerEn, "←","→"),
    `Elo Gap`    = paste( round(elo_mismatch), ifelse( elo_east<=elo_west, "←","→"))
  ) 

post_sheet <- match_sheet |> 
select( `Match` = matchNo, East = eastShikona, `Record E` = record_east, `Elo E` = elo_east, `Win Prob E` = pwin_east, Win,  West = westShikona, `Record W` = record_west,  `Elo W` = elo_west, `Win Prob W` = pwin_west, Surprisal = surprisal)


gt( post_sheet) |>
  tab_options(table.width = pct(90)) |> 
  tab_options(table.font.size = "14px") |> 
  fmt_number(
    columns = c( `Elo W`, `Elo E` ),
    use_seps = F,
    decimals = 0  # sets the number of decimal places
  ) |> 
  fmt_number(
    columns =  c( Surprisal, `Win Prob E`, `Win Prob W`),
    decimals = 2
  ) |> 
  cols_align(
    align = "center",
    columns = `Win`   # replace with your column
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(
      columns = c( `Win Prob E`, `Win`, `Win Prob W` )
    )
  )

```

